"""
Django settings for newspulsehq project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-+9_m2m_npqxfs@hywwywv702ukaf+qplf0o%2&ha6b!9b+2zd=",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'newspulsehqapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'newspulsehq.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "newspulsehqapp" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.debug",
                "django.template.context_processors.csrf",
                "newspulsehqapp.context_processors.site_categories",
                "newspulsehqapp.context_processors.adsense_settings",
            ],
        },
    },
]

WSGI_APPLICATION = 'newspulsehq.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "newspulsehqapp" / "static",
]

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

NEWS_API_KEY = os.environ.get("NEWS_API_KEY", "66d4890d489943edb0c6e8239326e12a")
GNEWS_API_KEY = os.environ.get("GNEWS_API_KEY", "ae5f387e6df1851248e32ea2a1f1dc51")


# Automated hourly news refresh (see newspulsehqapp/scheduler.py).
# Set ENABLE_NEWS_SCHEDULER=false in the environment to disable, e.g.
# when running one-off scripts or in an environment with its own cron.
ENABLE_NEWS_SCHEDULER = os.environ.get(
    "ENABLE_NEWS_SCHEDULER", "true"
).lower() == "true"


# Monetisation
# -------------------------------------------------------------------
# Google AdSense. Set these in the environment once you have a
# publisher account; the site renders no ad markup until ADSENSE_CLIENT_ID
# is configured, so leaving them unset is safe.
ADSENSE_CLIENT_ID = os.environ.get("ADSENSE_CLIENT_ID", "")

ADSENSE_SLOT_HOME = os.environ.get("ADSENSE_SLOT_HOME", "")
ADSENSE_SLOT_ARTICLE = os.environ.get("ADSENSE_SLOT_ARTICLE", "")
ADSENSE_SLOT_CATEGORY = os.environ.get("ADSENSE_SLOT_CATEGORY", "")

