# Generated by Django 6.1 on 2026-08-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspulsehqapp', '0003_comment_articlelike'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
