# Generated by Django 6.1 on 2026-08-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspulsehqapp', '0004_article_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
