# Generated by Django 6.1 on 2026-08-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspulsehqapp', '0005_article_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
