# Generated by Django 5.2.17 on 2026-09-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspulsehqapp", "0006_article_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="SponsoredAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("advertiser_name", models.CharField(max_length=150)),
                ("headline", models.CharField(max_length=200)),
                ("body", models.CharField(blank=True, max_length=300)),
                (
                    "destination_url",
                    models.URLField(
                        help_text="Where visitors land after clicking the ad."
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="sponsored_ads/"
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("home_feed", "Homepage — between hero and latest stories"),
                            ("category_top", "Category page — top banner"),
                            ("article_inline", "Article page — inline within content"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Higher priority ads are shown first when several are active for a placement.",
                    ),
                ),
                ("impression_count", models.PositiveIntegerField(default=0)),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order", "name"],
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="base_likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Lower numbers appear first in navigation and on the homepage.",
            ),
        ),
    ]
